### ISSUE TITLE
How to access HttpContext in the Giraffe wrapper?

### ISSUE THREAD

**Issue by vasily-kirichenko** [Zaid-Ajaj/Fable.Remoting#5] opened 2017-12-26 10:25 UTC
I have some handlers that need to access `HttpContext`, like this:
```fsharp
route "/user" (fun next ctx ->
    if ctx.User.Identity.IsAuthenticated then
        json (Some ctx.User.Identity.Name) next ctx
    else json None next ctx
)
```
Is it possible to port it?

**Comment by Zaid-Ajaj** [comment] 2017-12-26 15:22
Unfortunately, as of now, it not possible to access the HttpContext. This is by design and it is the whole idea of this library: Abstract Http and only think in terms of types and pure functions. Allowing the user to read HttpContext would make for a leaky abstraction. Now I only read data from incoming requests using the bare minimum of the request body and nothing else. 

Your problem is something I have thought about since the very beginning. Here are some solutions

### Solution 1
If you need to make sure that the `HttpHandler` generated by Fable.Remoting is accessed only after the user has authenticated, you can just do `route "/user-authenticated" >=> fableWebPart` but the caveat is that you won't be able to access the user for the `fableWebPart`

### Solution 2
Another solution I thought of would be to *model* the protocol with authorized requests in mind, [this comment](https://github.com/SAFE-Stack/SAFE-BookStore/issues/112#issuecomment-307641466) explains everything, it requires using stateless authentication with something like JWT and you would send the auth token to the server everytime you make an authenticated request. (My preferred way of working with authentication)

I am open to suggestions and I am willing to work on a solution that makes contextualized requests easier to work with. 

### Suggestion 1
Allowing access to the HttpContext is one solution but I would rather not go that way. It would look very unnatural to work with, for example I was thinking that types of functions using a context would look like `Context<'A> -> Async<'B>` or `'A -> Context -> Async<'B>` instead of just `'A -> Async<'B>` but then I would to have to find a way to make the client to worry about the `Context<A>` when sending arguments to server. 

### Suggestion 2
Another way that *could* work better is to have *dependent* protocols: record types with a generic type such as `IServer<'User>` where the functions of such protocol/record would be of the shape `'A -> 'User -> Async<'B>`. When constructing such protocol, the user would provide a function `HttpContext -> 'User` that reads the information from the request

If you have *anything* in mind that would fit nicely into the "pure functions and type" school of thought, please let me know!

**Comment by Zaid-Ajaj** [comment] 2017-12-26 15:33
Now that I am thinking more on the subject, here is another solution that would make user data available by your functions using partial application:

```fs
let fableHandlerWithUser (user: User) =
 let protocol = { 
    // unit -> Async<string>
    getUserName = fun () ->
       async { return user.Identity.Name }
}
```
Now you only need to pass the user from previous handler to the this *dependent* handler. Not sure how this would work Giraffe but I can take a look

**Comment by Zaid-Ajaj** [comment] 2018-01-01 15:47
I assume this question is answered so I will close this issue for now.

**Closed by Zaid-Ajaj** 2018-01-01 15:47 UTC
