### ISSUE TITLE
float32 does not work

### ISSUE THREAD

**Issue by 0x53A** [Zaid-Ajaj/Fable.Remoting#95] opened 2018-11-09 11:20 UTC
I wanted to transmit a float32 array over Fable.Remoting, but always got 

```
Error: "Cannot convert ["JNumber",0] to ["Any",null]"
```

![grafik](https://user-images.githubusercontent.com/4236651/48259832-96caf980-e419-11e8-8c54-2afd29c1aa6e.png)

### Workaround

After changing all of them to float (64 bit), it works

### Root cause 

I would guess this is maybe because Fable.SimpleJson doesn't handle System.Single?

![grafik](https://user-images.githubusercontent.com/4236651/48259907-c8dc5b80-e419-11e8-9cf4-072961cdbfe4.png)

**Comment by Zaid-Ajaj** [comment] 2018-11-09 12:44
Thanks for the report, this should be an easy fix indeed. The root cause is almost always in SimpleJson as the library handles all JSON serialization business, I will try to fix it later today

**Comment by Zaid-Ajaj** [comment] 2018-11-10 16:07
Fixed in [SimpleJson/PR-18](https://github.com/Zaid-Ajaj/Fable.SimpleJson/pull/18), will patch remoting client as soon the nuget is ready

**Closed** 2018-11-10 19:03 UTC

**Comment by Zaid-Ajaj** [comment] 2018-11-10 19:06
Fix and published in version `4.5.3` of the remoting client, can you please update and check whether the issue persists?
